version: "3"

services:
  deep-ai-api:
    build: ./src
    container_name: deep-ai-api
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py migrate"
    volumes:
      - ./src:/code
    depends_on:
      - deep-ai-db
    ports:
      - 8000:8000
    links:
      - deep-ai-db:deep-ai-db
    networks:
      - defaultnetwork
  deep-ai-db:
    image: postgres
    container_name: deep-ai-db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - defaultnetwork
  deep-ai-web-server:
    build: ./nginx/dev
    container_name: deep-ai-web-server
    ports:
      - 80:80
    volumes:
      - ./data/logs/nginx/:/var/log/nginx/
    depends_on:
      - deep-ai-api
    networks:
      - defaultnetwork
networks:
  defaultnetwork:
    driver: bridge
volumes:
  db-store:
