version: "3"

services:
  deep-ai-api:
    build: ./src
    container_name: deep-ai-api
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py migrate"
    volumes:
      - ./src:/code
    depends_on:
      - deep-ai-db
    ports:
      - 8000:8000
    links:
      - deep-ai-db:deep-ai-db
    networks:
      - defaultnetwork
  deep-ai-db:
    image: postgres
    container_name: deep-ai-db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - defaultnetwork
  deep-ai-web-server:
    build: ./nginx/prod
    container_name: deep-ai-web-server
    volumes:
      - ./data/logs/nginx/:/var/log/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    links:
      - deep-ai-api
    depends_on:
      - deep-ai-api
    networks:
      - defaultnetwork
  deep-ai-ssl-certificate:
    image: certbot/certbot
    container_name: deep-ai-ssl-certificate
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - deep-ai-web-server
    networks:
      - defaultnetwork
networks:
  defaultnetwork:
    driver: bridge
volumes:
  db-store:
