# Generated by Django 3.2.8 on 2023-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
