# Generated by Django 3.2.8 on 2023-05-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230524_1558'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='content',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='related_content', to='user.User'),
        ),
    ]
