# Generated by Django 3.2.8 on 2021-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20211103_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='issue',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='log',
            name='solution',
            field=models.URLField(max_length=512),
        ),
    ]
