# Generated by Django 3.2.8 on 2023-05-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20230526_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='like',
        ),
    ]
