# Generated by Django 3.2.8 on 2023-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_content_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='prompt',
            field=models.TextField(),
        ),
    ]
