# Generated by Django 3.2.8 on 2025-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='workflow_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
