# Generated by Django 3.2.8 on 2022-01-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_log_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='solution',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='issue',
            new_name='title',
        ),
    ]
