# Generated by Django 3.2.8 on 2021-11-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='log',
            name='issue',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='log',
            name='solution',
            field=models.URLField(default='', max_length=512),
        ),
    ]
