# Generated by Django 3.2.8 on 2022-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_logs'),
        ('log', '0006_auto_20220115_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='categories',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
